import Image from "next/image";
import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GameProvider } from "@/context/GameContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative h-full w-full antialiased`}
      >
        <GameProvider>{children}</GameProvider>

        <Image
          src="/img/bg_temp.jpg"
          alt=""
          className="absolute top-0 left-0 w-full h-full object-cover"
          fill
          priority
          role="presentation"
        />
      </body>
    </html>
  );
}
