
import type { Metadata } from "next";


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GameProvider } from "@/context/GameContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "https://next-holiday-memory.vercel.app"
  ),
  title: "Holiday Memory Game",
  description:
    "The holidays are about creating special memories, so how about a game to test just that... Good luck!",
  openGraph: {
    title: "Holiday Memory Game",
    description:
      "The holidays are about creating special memories, so how about a game to test just that... Good luck!",
    images: [
      {
        url: "/meta-og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Holiday Memory Game",
        type: "image/jpeg",
      },
    ],
  },
  icons: {
    icon: [
      { url: "/favicon_16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon_32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    apple: [
      {
        url: "/apple-touch-icon-152x152.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
    other: [
      {
        rel: "android-chrome",
        url: "/apple-touch-icon-152x152.png",
        sizes: "152x152",
        type: "image/png",
      },
      {
        rel: "android-chrome",
        url: "/apple-touch-icon-144x144.png",
        sizes: "144x144",
        type: "image/png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative h-full w-full antialiased bg-cover bg-no-repeat bg-center`}
        style={{ backgroundImage: "url('/img/bg_temp.jpg')" }}
      >
        <GameProvider>{children}</GameProvider>

        {/* <Image
          src="/img/bg_temp.jpg"
          alt=""
          className="absolute top-0 left-0 w-full h-full object-cover"
          fill
          priority
          role="presentation"
        /> */}
      </body>
    </html>
  );
}
